project:
  type: website

website:
  title: "#BIBC2025"
  page-footer: |
     Sponsored by<br><br>
     <table style="width:100%!important;">
     <tr><th>PLATINUM</th><th style="width:50%!important;">GOLD</th><th>SUPPORTER</th></tr>
     <tr>
     <td>![](/images/sponsors/ANU_Primary_Horizontal_GoldBlack.png){fig-alt="Australian National University" height="4em"}</td>
     <td>![](/images/sponsors/GRDC_Logo_Primary_Default.jpg){fig-alt="Grains Research and Development Corporation" height="4em"}![](/images/sponsors/UoA-Logo-Primary-RGB-Large.png){fig-alt="University of Auckland" height="4em"}</td>
     <td>![ACT Branch](/images/sponsors/SSA_Logotype_MAIN USE.jpg){fig-alt="Statistical Society of Australia ACT Branch" height="4em"}</td>
     </tr>
     </table>

       <br><br>
     Biometrics in the Bush Capital {{< fa solid landmark >}} Canberra, Australia
  favicon: favicon.ico
  repo-url: https://github.com/IBS-AR/conference2025
  repo-actions: [edit, issue]
  sidebar:
    logo: logo-ibs-ar.svg
  navbar:
    logo: logo-ibs-ar.svg
    left:
      - href: index.qmd
        text: Home
      - text: Program
        menu:
          #- href: schedule.qmd
          - href: book/sessions.qmd
            text: Schedule
          - href: keynote.qmd
          - href: invited.qmd
          - href: workshop.qmd
      - social.qmd
      - text: Participation
        menu:
          - href: abstract.qmd
          - href: https://membership.biometricsociety.org.au/event-6157046
            text: Registration
          - href: travel.qmd
          - href: venue.qmd
          - href: presenters.qmd
          - href: accommodation.qmd
          - href: sponsorship.qmd
          - href: coc.qmd
      - text: About
        menu:
        - organisers.qmd
        - contact.qmd
        - dates.qmd
        - history.qmd
    tools:
      - icon: github
        url: https://github.com/IBS-AR/conference2025
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    title-block-banner: true
